package com.spbtablo;

import javax.swing.*;
import java.awt.*;

public class PreviewScreen {
    public JPanel panelImgPreview;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelImgPreview = new JPanel();
        panelImgPreview.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        panelImgPreview.setAutoscrolls(false);
        panelImgPreview.setBackground(new Color(-1));
        panelImgPreview.setMaximumSize(new Dimension(640, 360));
        panelImgPreview.setMinimumSize(new Dimension(640, 360));
        panelImgPreview.setPreferredSize(new Dimension(640, 360));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelImgPreview;
    }
}
